# Generated by Django 2.2.13 on 2020-06-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myuser.managers
import myuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='Voornaam')),
                ('last_name', models.CharField(max_length=30, verbose_name='Achternaam')),
                ('show_blogger', models.BooleanField(default=True, help_text='Designates whether the blogger is displayed in the list of all bloggers', verbose_name='Show in Bloggers list')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=myuser.models.get_blogger_logo)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', myuser.managers.BloggerManager()),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=myuser.models.get_blog_logo)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affilations_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliated Blog',
                'verbose_name_plural': 'Affiliated Blogs',
            },
        ),
        migrations.AddField(
            model_name='blogger',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger', to='myuser.AffiliatedBlog'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogger',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
