# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
