# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20170630_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogger', to='myuser.AffiliatedBlog'),
        ),
    ]
