# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20170701_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='twitter',
        ),
        migrations.AddField(
            model_name='affiliatedblog',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='affiliatedblog',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='affiliatedblog',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
