# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20170702_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Achternaam'),
        ),
    ]
