# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:22
from __future__ import unicode_literals

import apps.blog.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('teaser', tinymce.models.HTMLField(blank=True, default=b'', verbose_name='Teaser')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.get_post_image, verbose_name='Teaser Photo')),
                ('url', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text=b'Should this post be shown in the featured list?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='Date Published')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
