# Generated by Django 2.2.13 on 2020-06-26 20:28

import blog.models
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('teaser', tinymce.models.HTMLField(blank=True, default='Inleiding/teaser voor je blogpost van max. 750 karakters', max_length=750, verbose_name='Teaser')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.get_post_image, verbose_name='Teaser foto')),
                ('url', models.URLField(max_length=300)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post is gepubliceerd op')),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Should this post be shown in the featured list?')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='Date Published')),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date/Time Last Changed')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
