# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:41
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170625_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post is gepubliceerd op'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_post_image, verbose_name='Teaser foto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=tinymce.models.HTMLField(blank=True, default=b'Inleiding/teaser voor je blogpost van max. 500 woorden', verbose_name='Teaser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
