# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170627_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Created'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Last Changed'),
        ),
    ]
