# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170628_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
