# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=tinymce.models.HTMLField(blank=True, default=b'Inleiding/teaser voor je blogpost van max. 750 karakters', max_length=750, verbose_name='Teaser'),
        ),
    ]
