# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170704_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Should this post be shown in the featured list?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=tinymce.models.HTMLField(blank=True, default='Inleiding/teaser voor je blogpost van max. 750 karakters', max_length=750, verbose_name='Teaser'),
        ),
    ]
