# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:22
from __future__ import unicode_literals

import pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', tinymce.models.HTMLField(blank=True, help_text=b'Introduction about Fairblogs for on the About Us page', verbose_name='About Us')),
                ('about_fairfrog', tinymce.models.HTMLField(blank=True, verbose_name='About Fairfrog')),
                ('url_fairfrog', models.URLField(blank=True, help_text=b'Website url')),
                ('logo_fairfrog', models.ImageField(blank=True, null=True, upload_to=pages.models.get_company_logo)),
                ('about_sociii', tinymce.models.HTMLField(blank=True, verbose_name='About Sociii')),
                ('url_sociii', models.URLField(blank=True, help_text=b'Website url')),
                ('logo_sociii', models.ImageField(blank=True, null=True, upload_to=pages.models.get_company_logo)),
                ('about_projectcece', tinymce.models.HTMLField(blank=True, verbose_name='About Project Cece')),
                ('url_projectcece', models.URLField(blank=True, help_text=b'Website url')),
                ('logo_projectcece', models.ImageField(blank=True, null=True, upload_to=pages.models.get_company_logo)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aboutus_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('webmaster_email', models.EmailField(max_length=254, verbose_name='Webmaster Email')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('postbox', models.CharField(max_length=256, verbose_name='PO Box')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactinfo_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', tinymce.models.HTMLField(blank=True, verbose_name='Privacy Policy')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
