# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20170704_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', tinymce.models.HTMLField(blank=True, verbose_name='Disclaimer')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclaimer_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disclaimer',
                'verbose_name_plural': 'Disclaimer',
            },
        ),
    ]
