# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=tinymce.models.HTMLField(blank=True, help_text='Bovenste gedeelte over FairBlogs op de about pagina.', verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_below',
            field=tinymce.models.HTMLField(blank=True, help_text='Onderste gedeelte over FairBlogs op de about pagina.', verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='url_fairfrog',
            field=models.URLField(blank=True, help_text='Website url'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='url_projectcece',
            field=models.URLField(blank=True, help_text='Website url'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='url_sociii',
            field=models.URLField(blank=True, help_text='Website url'),
        ),
    ]
